version: '3'

services:
  recylinkapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nest-graphql
    container_name: RecylinkApp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      MONGODB: ${MONGODB}


  db:
    image: mongo:5
    container_name: recylink-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: recylink
    volumes:
      - ./data/db:/data/db
